name: build

on:
  push:
    paths-ignore:
      - "**/*.md"
      - ".env*"

env:
  NAME: debug

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3

      - name: Build Containers
        id: build-containers
        shell: bash
        run: |
          nix build --out-link result-container && docker load < result-container

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider:  ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gh-${{env.NAME}}@nais-io.iam.gserviceaccount.com
          token_format: access_token

      - name: "Handle auth failure"
        if: ${{ failure() && steps.auth.outcome == 'failure' }}
        shell: bash
        run: |
          cat <<EOF
          ::error ::Failed to authenticate to Google Cloud.
          EOF

      - name: "Login to registry"
        id: login-to-registry
        uses: docker/login-action@v3
        with:
          registry: "europe-north1-docker.pkg.dev"
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Push image to registry
        id: push
        shell: bash
        run: |
          docker push europe-north1-docker.pkg.dev/nais-io/nais/images/${{env.NAME}}:latest
